export const siteConfig = {
  name: "Udemy Course Bangladesh",
  shortName: "UCB",
  domain: "https://udemycoursebd.com",
  affiliateLink: "https://trk.udemy.com/xJmW2A",
  facebook: "https://www.facebook.com/udemycoursebangladesh",
  facebookMessage: "https://m.me/udemycoursebangladesh",
  instagram: "https://www.instagram.com/udemybangladesh/",
  whatsappNumber: "+8801338770408",
  whatsappLink: "https://wa.me/8801338770408",
  phone: "+8801735857535",
  locale: "en_BD",
  country: "Bangladesh",
  address: "68-69 Concept Tower, Greenroad, Dhaka 1205, Bangladesh",
};
